---
- name: Install PyYAML
  pip: name=pyyaml version={{ pyyaml_version }}

- name: Create container volume mount directories
  file: name={{ item.name }} state=directory
        mode=755 owner={{ item.owner | default(omit) }} group={{ item.group | default(omit) }}
        recurse=true
  with_items:
    - name: /var/cache/nexus
      group: 200
      owner: 200
    - name: "{{ service_home }}/nginx"
      owner: "{{ ansible_user }}"

- name: Add Nginx config
  copy: src=nexus.conf dest="{{ service_home }}/nginx/nexus.conf"

- name: Configure Nexus Docker Compose service
  docker_service:
    build: yes
    project_name: nexus
    state: present
    definition: "{{ service_definition }}"

- include_tasks: restore-backup.yml
  tags:
    - restore-backup
