---
- name: Add azavea user to Docker group
  user: name={{ docker_user }} group=docker

- name: Install python dependencies
  pip: name="{{ item.name }}" version="{{ item.version }}"
       state=present
  with_items: "{{ python_deps }}"

- name: Create container build directories
  file: name={{ item }} state=directory
        mode=755 owner=azavea group=1000
  with_items:
    - /var/cache/nexus
    - "{{ service_home }}/nginx"
    - "{{ service_home }}/nexus"


- name: Upload Docker build files
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - src: Dockerfile.nexus
      dest: "{{ service_home }}/nexus/Dockerfile"
    - src: Dockerfile.nginx
      dest: "{{ service_home }}/nginx/Dockerfile"
    - src: nexus.conf
      dest: "{{ service_home }}/nginx/nexus.conf"


- name: Download Nexus data from S3
  aws_s3: bucket="{{ nexus_data_bucket }}" object="nexus-data-backup.tar.gz"
          mode=get dest=/tmp/nexus-data-backup.tar.gz
          profile=default overwrite=different
  become_user: azavea
  register: nexus_data_updated

- name: Unpack nexus data
  unarchive: src=/tmp/nexus-data-backup.tar.gz dest=/
             remote_src=yes
  when: nexus_data_updated.changed

- name: Configure nexus service
  docker_service:
    build: yes
    project_name: "nexus"
    state: "present"
    definition:
      version: "2"
      services:
        nexus-nginx:
          image: "nginx:1.14"
          networks:
            - "nexus"
          ports:
            - "80:80"
          volumes:
            - "{{ service_home }}/nginx/nexus.conf:/etc/nginx/conf.d/default.conf"
          restart: on-failure
          logging:
            driver: syslog
            options:
              tag: nexus-nginx
        nexus-server:
          build:
            context: "{{ service_home }}/nexus"
          networks:
            - "nexus"
          volumes:
            - /var/cache/nexus:/nexus-data
          restart: on-failure
          logging:
            driver: syslog
            options:
              tag: nexus-server
        data_copy:
          image: "alpine"
          networks:
            - "nexus"
          volumes:
            - "/var/cache/nexus/nexus-data:/src"
          command:
            - "sh"
            - "-c"
            - "chown -R 1000:1000 /src/"
          logging:
            driver: syslog
            options:
              tag: nexus-data-copy
      networks:
        nexus: